### ISSUE TITLE
feature request: mathesar: be able to use a secret

### ISSUE THREAD

**Issue by bbigras** [andrenarchy/helm-charts#9]
for `SECRET_KEY` and `POSTGRES_USER`.

Maybe something like what registry-1.docker.io/bitnamicharts keycloak uses:

```yaml
externalDatabase:
  existingSecret: "postgresql-cluster-app"
  existingSecretHostKey: "host"
  existingSecretPortKey: "port"
  existingSecretUserKey: "user"
  existingSecretDatabaseKey: "dbname"
  existingSecretPasswordKey: "password"
```
